### ISSUE TITLE
8 Teeth Nema 14 compatibility 

### ISSUE THREAD

**Issue by thomasfjen** [bythorsthunder/Voron_Mods#5]
Hey There!
I just discovered that I mistakenly ordered an 8 Teeth motor for the extruder when I wasn't able to dial in the gear backslash perfectly. Would it be possible to add a bit more wiggle room for 8 Teeth steppers?

Additionally an additional info about the motor gear tooth count would be appreciated, to help other to not order the wrong motors.

Kind regards,
Thomas

**Comment by bythorsthunder** [comment]
Thank you for the note.  Support has been added for both 6T and 8T motors and readme has been updated.
